name: ZebraTesterAction
description: Run performance tests using ZebraTester test plan
author: Praveen

branding:
  color: blue
  icon: feather

inputs:
  test-plan-path:
    required: true
    description: ZebraTester test plan to execute
  results-file:
    required: false
    description: Where to store the results, e.g., result.jtl
    default: result.jtl
  args:
    required: false
    description: Optional arguments for ZebraTester execution

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-n"
    - "-t"
    - "${{ inputs.test-plan-path }}"
    - "-l"
    - "${{ inputs.results-file }}"
    - ${{ inputs.args }}
